package jpa.vs.querydsl.test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import jpa.vs.querydsl.test.JPAExample;
import jpa.vs.querydsl.test.jpa.entity.Member;

public class JPATest {
	private Connection conn;
	private JPAExample test;
	@Before
	public void initializeDatabase() throws Exception {
		conn = DriverManager.getConnection("jdbc:h2:mem:/test", "sa", "");
		Statement st = conn.createStatement();
		st.execute(
				"create table Member (id bigint generated by default as identity, address varchar(255), name varchar(255), primary key (id))");
		st.execute("create sequence hibernate_sequence start with 1 increment by 1");
		st.execute("insert into Member (address, name) values ('Small', 'Budapest')"); 
		conn.commit();
		test=new JPAExample();
	}

	@Test
	public void test() {
		long timeStart=System.currentTimeMillis();
		List<Member> testRead = test.testRead();
		org.junit.Assert.assertEquals(1,testRead.size());
		long timeEnd=System.currentTimeMillis();
		System.out.println("JPA one entity read runs: "+(timeEnd-timeStart)+ " ms");
	}

	@After
	public void after() throws SQLException {
		conn.close();
		test.close();
	}
}
