package jpa.vs.querydsl.test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import jpa.vs.querydsl.test.QuerydslExample;
import jpa.vs.querydsl.test.dto.MemberDTO;

public class QuerydslTest {
	private Connection conn;
	private QuerydslExample testClass;
	
	@Before
	public void initializeDatabase() throws Exception {
		conn = DriverManager.getConnection("jdbc:h2:mem:/test", "sa", "");
		Statement st = conn.createStatement();
		st.execute(
				"create table Member (id bigint generated by default as identity, address varchar(255), name varchar(255), primary key (id))");
		st.execute("insert into Member (address, name) values ('Small', 'Budapest')");
		conn.commit();
		testClass=new QuerydslExample();
	}

	@Test
	public void test() throws Exception {
		long timeStart=System.currentTimeMillis();
		List<MemberDTO> members = testClass.getMembers();
		org.junit.Assert.assertEquals(1,members.size());
		long timeEnd=System.currentTimeMillis();
		System.out.println("Querydsl one entity read runs: "+(timeEnd-timeStart)+ " ms");
	}

	@After
	public void after() throws SQLException {
		testClass.close();
		conn.close();
	}
}
